on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 */2 * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          pull: true
          push: true
          no-cache: true
          tags: r3aper/nextcloud:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
